version: "3.9"
services:
  flask:
    build:
      context: ./docker
    container_name: flask
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    environment:
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port 80
